### PR TITLE
feat: Add support for new lts version of 12.2, 13.3 and 14.3

### PR DESCRIPTION
**Pull request by JeppeBlixen**
## What type of PR is this? (check all applicable)
- Feature

### Overview
Add support for new databricks lts versions 12.2 and 13.3 to testing pipeline.

### CODE REVIEW

**Comment by mrmasterplan** [comment]
consider merging with https://github.com/spetlr-org/spetlr/pull/103 or at lease see if you want to take inspiration from there.

**Comment by JeppeBlixen** [comment]
@mrmasterplan I saw your PR, but after i had done the work, i will merge the changes.

**Review by LauJohansson — APPROVED** [review]

**Review by MartinBoge — APPROVED** [review]

**Comment by LauJohansson** [comment]
This PR also solves issue #128

**Comment by FarBo** [comment]
Now we test 14.3 in this PR #177 
We are also considering to only support new versions. Should we close this PR? @JeppeBlixen

**Comment by mrmasterplan** [comment]
The deployment is completely changed and 14.3 is tested in PR #185 
I suggest that we mark this branch as abandonned and close the PR without merge.

**Comment by JeppeBlixen** [comment]
I will close this PR

**Comment by JeppeBlixen** [comment]
I will close this PR

**Comment by LauJohansson** [comment]
Agree!

**Pull request closed without merging**
