### PR TITLE
fix: move transformers

### PR DESCRIPTION
**Pull request by LauJohansson**
## What type of PR is this? (check all applicable)

- Refactor

### Overview
There are two transformers folders.
This is awful. I have merged the folders into one under /etl/

### What is the current behavior?
Two transformer folders

### What is the new behavior?
One folder: spetlr/etl/transformers

### Does this PR introduce a breaking change?
Paths will change!

### CODE REVIEW

**Comment by JeppeBlixen** [comment]
Also increment the version, due to breaking change

**Comment by LauJohansson** [comment]
> Also increment the version, due to breaking change

A major bump?

**Comment by JeppeBlixen** [comment]
If the init in transformers are kept, i think a minor is okey. If not it is truly breaking, i think it should be a major.

**Comment by JeppeBlixen** [comment]
> > Also increment the version, due to breaking change
> 
> A major bump?

If the init in transformers are kept, i think a minor is okey. If not it is truly breaking, i think it should be a major.

**Comment by LauJohansson** [comment]
@LauJohansson  note self - consider keeping the init in the legacy folder

**Review by JeppeBlixen — APPROVED** [review]

**Pull request merged**
