### PR TITLE
Distinguish user agent

### PR DESCRIPTION
**Pull request by nfx**
Add product name to all requests made via Databricks SDK

### CODE REVIEW

**Comment by nfx** [comment]
@mrmasterplan ^ is it also easy to add spetlr version to workspace client?

**Comment by mrmasterplan** [comment]
It seems you are missing black formatting. You can easily access the spetlr version as `spetlr.__version__`.
Thank you for your contribution.

**Comment by LauJohansson** [comment]
Hi @nfx,
Thanks for your contribution.

**Comment by LauJohansson** [comment]
@nfx You are welcome to reach out if you need assistance.

**Comment by LauJohansson** [comment]
I have made an implementation in #77.

**Comment by LauJohansson** [comment]
I will close this since #77 is merged.

**Pull request closed without merging**
