### PR TITLE
Migrate to unity catalog and terraform

### PR DESCRIPTION
**Pull request by FarBo**
## What type of PR is this?

- Refactor
- Bug Fix
- Optimization
- Deployment (Azure, CI/CD, PowerShell, ...)

## Description

- Introduce a test deployment with full Unity Catalog
- Change the spetlr version to be the same as the Databricks Runtime Version used in testing - 14.3.* for now
- Test only on 1 DBR version
- Make Speltr UC compatible (see below)
- Change the test deployment to be completely in terraform
- SQL server test were not ported to terraform yet, we invite future PRs to re-introduce this part of the tests.
- 

### Functional changes to Speltr

- The DeltaHandle by default no longer reads or writes by path. All read and writes are done using the name. 
         Unity Catalog tables are either managed, residing in UC managed storage or external (i.e. residing in storage that is known to UC, but not exposed to the user.) In both cases UC wants the user to go trough UC when accessing the table so that permissions can be applied. Therefore all direct access to the underlying data (regardless if that may save a few milliseconds) is not allowed.
- SQL server classes and some other code areas have been marked as deprecated for the simple reason that they are untested. The code has not been changed from previous versions and can still be used.
- Azure tag access is just a convenience method to access azure workspace resource tags in code.
- The Version has been increased to 14.3.0 to align with the DBR version that we test with.

### Deployment

Deployment is split into several stages:
- Permanent resources (metastore_and_pemanent) deploys the metastore and the permanent resources (Cosmos account)
- "integration_resources" deploys all azure resources, the captain service principal and the workspace.
- "integration_databricks" then uses that workspace API and deploys the catalog, workspace association, external locations and permissions so that the SPN can deploy the test job
- Test job submission is a simple step. The spetlr-tools repos could in fact use the pipeline to here and deploy its own set of commands at this point.

## Next steps after this

- Sql Server tests were taken out to descope the transformation. The powershell code has been left in the repo to serve as a reference for when these test resources are ported into terraform.
- Create a cleanup pipeline that deletes the captains and catalogs from databricks. Currently the tests leak 1 catalog and 1 databricks service principal on each run. They can be deleted by administrators. A cleanup script is needed but not critical.

### CODE REVIEW

**Comment by mrmasterplan** [comment]
Work completed:
- integration resource as well as databricks deployment is now based on local terraform state
- Deployments will be forgotten and need to be cleaned up outside terraform. This is for speedup of the pipeline.
- Azure cleanup script is done.
- Databricks cleanup (Catalogs, credentials, SPNs) is TODO.

**Comment by LauJohansson** [comment]
> Work completed:
> 
> * integration resource as well as databricks deployment is now based on local terraform state
> * Deployments will be forgotten and need to be cleaned up outside terraform. This is for speedup of the pipeline.
> * Azure cleanup script is done.
> * Databricks cleanup (Catalogs, credentials, SPNs) is TODO.
> 
> Next step:
> 
> * pipeline fails on missing permission to create databricks_storage_credential.ex_storage_cred.

The Databricks cleanup can maybe be done by using terraform destroy?

**Comment by mrmasterplan** [comment]
Re: @LauJohansson I intentionally went away from terraform destroy. Terraform destroy carefully rolls back all changes and waits until this has been completed. We use new names every run, so there is no collision. By simply deleting the resources, we save about 10 minutes of pipeline runtime. I would prefer not to go back to using terraform destroy.

**Comment by mrmasterplan** [comment]
Development Notes:
- I simplified the deployment to only 1 catalog. This is my preferred way 1 catalog to 1 workspace sharing the same name.
- During deployment, the pipeline identity will be used. This is already an account admin.
- TODO: for running, the captain needs read and write access to the catalog and nothing else. This needs a new group.
- The captain should not need account access.

**Comment by mrmasterplan** [comment]
Current state: Test job is launched but gives error: Cannot read the python file /Volumes/spetlr114571358001/volumes/init/main.py.

The library is correctly installed from the same volume, and logging into the workspace I can download main.py from the given location.

I do not currently understand the problem and am going to let it be for now and come back to it in a a few days. meanwhile, here are the driver logs:
[stderr (2).txt](https://github.com/user-attachments/files/17473895/stderr.2.txt)
[log4j-active (3).txt](https://github.com/user-attachments/files/17473944/log4j-active.3.txt)
[stdout (2).txt](https://github.com/user-attachments/files/17473930/stdout.2.txt)

**Comment by mrmasterplan** [comment]
Status: I just need to tune the test main job a little bit. The test job launches and output can be seen. Unity catalog setup seems good on inspection.

**Comment by mrmasterplan** [comment]
Status:
The deployment is working. The test job is runnning. All the test now need to be changed to actually work with unity catalog.

**Comment by mrmasterplan** [comment]
This PR is ready to merge. Please review.

**Pull request closed without merging**
